name: Build APK

on:
  push:
    branches:
      - master  # 或者你想要自动构建的分支

  workflow_dispatch:
    inputs:
      name:
        description: 'Manual trigger input'
        required: true
        default: 'default input'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
